// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package com.github.chengpan.proto;

/**
 * Protobuf type {@code com.github.chengpan.proto.Task}
 */
public final class Task extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.chengpan.proto.Task)
    TaskOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Task.newBuilder() to construct.
  private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Task() {
    id_ = "";
    blob_ = com.google.protobuf.ByteString.EMPTY;
    consumerId_ = "";
    callbackUrl_ = "";
    senderId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Task();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Task(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              meta_ = com.google.protobuf.MapField.newMapField(
                  MetaDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            meta__ = input.readMessage(
                MetaDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            meta_.getMutableMap().put(
                meta__.getKey(), meta__.getValue());
            break;
          }
          case 26: {

            blob_ = input.readBytes();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            consumerId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            callbackUrl_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            senderId_ = s;
            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dueAt_ != null) {
              subBuilder = dueAt_.toBuilder();
            }
            dueAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dueAt_);
              dueAt_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_Task_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetMeta();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_Task_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.chengpan.proto.Task.class, com.github.chengpan.proto.Task.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * used for deduplication with consumer_id
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * used for deduplication with consumer_id
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int META_FIELD_NUMBER = 2;
  private static final class MetaDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_Task_MetaEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> meta_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMeta() {
    if (meta_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetaDefaultEntryHolder.defaultEntry);
    }
    return meta_;
  }

  public int getMetaCount() {
    return internalGetMeta().getMap().size();
  }
  /**
   * <pre>
   * readable info
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */

  @java.lang.Override
  public boolean containsMeta(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMeta().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetaMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMeta() {
    return getMetaMap();
  }
  /**
   * <pre>
   * readable info
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
    return internalGetMeta().getMap();
  }
  /**
   * <pre>
   * readable info
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getMetaOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMeta().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * readable info
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getMetaOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMeta().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int BLOB_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString blob_;
  /**
   * <pre>
   * binary body
   * </pre>
   *
   * <code>bytes blob = 3;</code>
   * @return The blob.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBlob() {
    return blob_;
  }

  public static final int CONSUMER_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object consumerId_;
  /**
   * <pre>
   * consumer signature which should be interested in this task when it is due. eg: com.git.pcheng.consumers.email#sendToSubscriber
   * </pre>
   *
   * <code>string consumer_id = 4;</code>
   * @return The consumerId.
   */
  @java.lang.Override
  public java.lang.String getConsumerId() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consumerId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * consumer signature which should be interested in this task when it is due. eg: com.git.pcheng.consumers.email#sendToSubscriber
   * </pre>
   *
   * <code>string consumer_id = 4;</code>
   * @return The bytes for consumerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConsumerIdBytes() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consumerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLBACK_URL_FIELD_NUMBER = 5;
  private volatile java.lang.Object callbackUrl_;
  /**
   * <pre>
   * for http callback
   * </pre>
   *
   * <code>string callback_url = 5;</code>
   * @return The callbackUrl.
   */
  @java.lang.Override
  public java.lang.String getCallbackUrl() {
    java.lang.Object ref = callbackUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callbackUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * for http callback
   * </pre>
   *
   * <code>string callback_url = 5;</code>
   * @return The bytes for callbackUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCallbackUrlBytes() {
    java.lang.Object ref = callbackUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callbackUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_ID_FIELD_NUMBER = 6;
  private volatile java.lang.Object senderId_;
  /**
   * <pre>
   * sender signature
   * </pre>
   *
   * <code>string sender_id = 6;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public java.lang.String getSenderId() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * sender signature
   * </pre>
   *
   * <code>string sender_id = 6;</code>
   * @return The bytes for senderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderIdBytes() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DUE_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp dueAt_;
  /**
   * <pre>
   * when should this task be done,aka，callback invoked
   * </pre>
   *
   * <code>.google.protobuf.Timestamp due_at = 7;</code>
   * @return Whether the dueAt field is set.
   */
  @java.lang.Override
  public boolean hasDueAt() {
    return dueAt_ != null;
  }
  /**
   * <pre>
   * when should this task be done,aka，callback invoked
   * </pre>
   *
   * <code>.google.protobuf.Timestamp due_at = 7;</code>
   * @return The dueAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDueAt() {
    return dueAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dueAt_;
  }
  /**
   * <pre>
   * when should this task be done,aka，callback invoked
   * </pre>
   *
   * <code>.google.protobuf.Timestamp due_at = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDueAtOrBuilder() {
    return getDueAt();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMeta(),
        MetaDefaultEntryHolder.defaultEntry,
        2);
    if (!blob_.isEmpty()) {
      output.writeBytes(3, blob_);
    }
    if (!getConsumerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, consumerId_);
    }
    if (!getCallbackUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, callbackUrl_);
    }
    if (!getSenderIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, senderId_);
    }
    if (dueAt_ != null) {
      output.writeMessage(7, getDueAt());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMeta().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      meta__ = MetaDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, meta__);
    }
    if (!blob_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, blob_);
    }
    if (!getConsumerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, consumerId_);
    }
    if (!getCallbackUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, callbackUrl_);
    }
    if (!getSenderIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, senderId_);
    }
    if (dueAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDueAt());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.chengpan.proto.Task)) {
      return super.equals(obj);
    }
    com.github.chengpan.proto.Task other = (com.github.chengpan.proto.Task) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!internalGetMeta().equals(
        other.internalGetMeta())) return false;
    if (!getBlob()
        .equals(other.getBlob())) return false;
    if (!getConsumerId()
        .equals(other.getConsumerId())) return false;
    if (!getCallbackUrl()
        .equals(other.getCallbackUrl())) return false;
    if (!getSenderId()
        .equals(other.getSenderId())) return false;
    if (hasDueAt() != other.hasDueAt()) return false;
    if (hasDueAt()) {
      if (!getDueAt()
          .equals(other.getDueAt())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (!internalGetMeta().getMap().isEmpty()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMeta().hashCode();
    }
    hash = (37 * hash) + BLOB_FIELD_NUMBER;
    hash = (53 * hash) + getBlob().hashCode();
    hash = (37 * hash) + CONSUMER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConsumerId().hashCode();
    hash = (37 * hash) + CALLBACK_URL_FIELD_NUMBER;
    hash = (53 * hash) + getCallbackUrl().hashCode();
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderId().hashCode();
    if (hasDueAt()) {
      hash = (37 * hash) + DUE_AT_FIELD_NUMBER;
      hash = (53 * hash) + getDueAt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.chengpan.proto.Task parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.chengpan.proto.Task parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.chengpan.proto.Task parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.chengpan.proto.Task parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.chengpan.proto.Task parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.chengpan.proto.Task parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.chengpan.proto.Task parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.chengpan.proto.Task parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.chengpan.proto.Task parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.chengpan.proto.Task parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.chengpan.proto.Task parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.chengpan.proto.Task parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.chengpan.proto.Task prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.chengpan.proto.Task}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.chengpan.proto.Task)
      com.github.chengpan.proto.TaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_Task_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMeta();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableMeta();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.chengpan.proto.Task.class, com.github.chengpan.proto.Task.Builder.class);
    }

    // Construct using com.github.chengpan.proto.Task.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      internalGetMutableMeta().clear();
      blob_ = com.google.protobuf.ByteString.EMPTY;

      consumerId_ = "";

      callbackUrl_ = "";

      senderId_ = "";

      if (dueAtBuilder_ == null) {
        dueAt_ = null;
      } else {
        dueAt_ = null;
        dueAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_Task_descriptor;
    }

    @java.lang.Override
    public com.github.chengpan.proto.Task getDefaultInstanceForType() {
      return com.github.chengpan.proto.Task.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.chengpan.proto.Task build() {
      com.github.chengpan.proto.Task result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.chengpan.proto.Task buildPartial() {
      com.github.chengpan.proto.Task result = new com.github.chengpan.proto.Task(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.meta_ = internalGetMeta();
      result.meta_.makeImmutable();
      result.blob_ = blob_;
      result.consumerId_ = consumerId_;
      result.callbackUrl_ = callbackUrl_;
      result.senderId_ = senderId_;
      if (dueAtBuilder_ == null) {
        result.dueAt_ = dueAt_;
      } else {
        result.dueAt_ = dueAtBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.chengpan.proto.Task) {
        return mergeFrom((com.github.chengpan.proto.Task)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.chengpan.proto.Task other) {
      if (other == com.github.chengpan.proto.Task.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      internalGetMutableMeta().mergeFrom(
          other.internalGetMeta());
      if (other.getBlob() != com.google.protobuf.ByteString.EMPTY) {
        setBlob(other.getBlob());
      }
      if (!other.getConsumerId().isEmpty()) {
        consumerId_ = other.consumerId_;
        onChanged();
      }
      if (!other.getCallbackUrl().isEmpty()) {
        callbackUrl_ = other.callbackUrl_;
        onChanged();
      }
      if (!other.getSenderId().isEmpty()) {
        senderId_ = other.senderId_;
        onChanged();
      }
      if (other.hasDueAt()) {
        mergeDueAt(other.getDueAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.chengpan.proto.Task parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.chengpan.proto.Task) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * used for deduplication with consumer_id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * used for deduplication with consumer_id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * used for deduplication with consumer_id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * used for deduplication with consumer_id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * used for deduplication with consumer_id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> meta_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMeta() {
      if (meta_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaDefaultEntryHolder.defaultEntry);
      }
      return meta_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableMeta() {
      onChanged();;
      if (meta_ == null) {
        meta_ = com.google.protobuf.MapField.newMapField(
            MetaDefaultEntryHolder.defaultEntry);
      }
      if (!meta_.isMutable()) {
        meta_ = meta_.copy();
      }
      return meta_;
    }

    public int getMetaCount() {
      return internalGetMeta().getMap().size();
    }
    /**
     * <pre>
     * readable info
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */

    @java.lang.Override
    public boolean containsMeta(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMeta().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMeta() {
      return getMetaMap();
    }
    /**
     * <pre>
     * readable info
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
      return internalGetMeta().getMap();
    }
    /**
     * <pre>
     * readable info
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMeta().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * readable info
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMeta().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMeta() {
      internalGetMutableMeta().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * readable info
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */

    public Builder removeMeta(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMeta().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableMeta() {
      return internalGetMutableMeta().getMutableMap();
    }
    /**
     * <pre>
     * readable info
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    public Builder putMeta(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMeta().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * readable info
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */

    public Builder putAllMeta(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMeta().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.ByteString blob_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * binary body
     * </pre>
     *
     * <code>bytes blob = 3;</code>
     * @return The blob.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBlob() {
      return blob_;
    }
    /**
     * <pre>
     * binary body
     * </pre>
     *
     * <code>bytes blob = 3;</code>
     * @param value The blob to set.
     * @return This builder for chaining.
     */
    public Builder setBlob(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blob_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * binary body
     * </pre>
     *
     * <code>bytes blob = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlob() {
      
      blob_ = getDefaultInstance().getBlob();
      onChanged();
      return this;
    }

    private java.lang.Object consumerId_ = "";
    /**
     * <pre>
     * consumer signature which should be interested in this task when it is due. eg: com.git.pcheng.consumers.email#sendToSubscriber
     * </pre>
     *
     * <code>string consumer_id = 4;</code>
     * @return The consumerId.
     */
    public java.lang.String getConsumerId() {
      java.lang.Object ref = consumerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * consumer signature which should be interested in this task when it is due. eg: com.git.pcheng.consumers.email#sendToSubscriber
     * </pre>
     *
     * <code>string consumer_id = 4;</code>
     * @return The bytes for consumerId.
     */
    public com.google.protobuf.ByteString
        getConsumerIdBytes() {
      java.lang.Object ref = consumerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * consumer signature which should be interested in this task when it is due. eg: com.git.pcheng.consumers.email#sendToSubscriber
     * </pre>
     *
     * <code>string consumer_id = 4;</code>
     * @param value The consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      consumerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * consumer signature which should be interested in this task when it is due. eg: com.git.pcheng.consumers.email#sendToSubscriber
     * </pre>
     *
     * <code>string consumer_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearConsumerId() {
      
      consumerId_ = getDefaultInstance().getConsumerId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * consumer signature which should be interested in this task when it is due. eg: com.git.pcheng.consumers.email#sendToSubscriber
     * </pre>
     *
     * <code>string consumer_id = 4;</code>
     * @param value The bytes for consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      consumerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object callbackUrl_ = "";
    /**
     * <pre>
     * for http callback
     * </pre>
     *
     * <code>string callback_url = 5;</code>
     * @return The callbackUrl.
     */
    public java.lang.String getCallbackUrl() {
      java.lang.Object ref = callbackUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callbackUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * for http callback
     * </pre>
     *
     * <code>string callback_url = 5;</code>
     * @return The bytes for callbackUrl.
     */
    public com.google.protobuf.ByteString
        getCallbackUrlBytes() {
      java.lang.Object ref = callbackUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callbackUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * for http callback
     * </pre>
     *
     * <code>string callback_url = 5;</code>
     * @param value The callbackUrl to set.
     * @return This builder for chaining.
     */
    public Builder setCallbackUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      callbackUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * for http callback
     * </pre>
     *
     * <code>string callback_url = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCallbackUrl() {
      
      callbackUrl_ = getDefaultInstance().getCallbackUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * for http callback
     * </pre>
     *
     * <code>string callback_url = 5;</code>
     * @param value The bytes for callbackUrl to set.
     * @return This builder for chaining.
     */
    public Builder setCallbackUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      callbackUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object senderId_ = "";
    /**
     * <pre>
     * sender signature
     * </pre>
     *
     * <code>string sender_id = 6;</code>
     * @return The senderId.
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * sender signature
     * </pre>
     *
     * <code>string sender_id = 6;</code>
     * @return The bytes for senderId.
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * sender signature
     * </pre>
     *
     * <code>string sender_id = 6;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sender signature
     * </pre>
     *
     * <code>string sender_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      
      senderId_ = getDefaultInstance().getSenderId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sender signature
     * </pre>
     *
     * <code>string sender_id = 6;</code>
     * @param value The bytes for senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dueAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dueAtBuilder_;
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     * @return Whether the dueAt field is set.
     */
    public boolean hasDueAt() {
      return dueAtBuilder_ != null || dueAt_ != null;
    }
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     * @return The dueAt.
     */
    public com.google.protobuf.Timestamp getDueAt() {
      if (dueAtBuilder_ == null) {
        return dueAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dueAt_;
      } else {
        return dueAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     */
    public Builder setDueAt(com.google.protobuf.Timestamp value) {
      if (dueAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dueAt_ = value;
        onChanged();
      } else {
        dueAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     */
    public Builder setDueAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dueAtBuilder_ == null) {
        dueAt_ = builderForValue.build();
        onChanged();
      } else {
        dueAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     */
    public Builder mergeDueAt(com.google.protobuf.Timestamp value) {
      if (dueAtBuilder_ == null) {
        if (dueAt_ != null) {
          dueAt_ =
            com.google.protobuf.Timestamp.newBuilder(dueAt_).mergeFrom(value).buildPartial();
        } else {
          dueAt_ = value;
        }
        onChanged();
      } else {
        dueAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     */
    public Builder clearDueAt() {
      if (dueAtBuilder_ == null) {
        dueAt_ = null;
        onChanged();
      } else {
        dueAt_ = null;
        dueAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDueAtBuilder() {
      
      onChanged();
      return getDueAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDueAtOrBuilder() {
      if (dueAtBuilder_ != null) {
        return dueAtBuilder_.getMessageOrBuilder();
      } else {
        return dueAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dueAt_;
      }
    }
    /**
     * <pre>
     * when should this task be done,aka，callback invoked
     * </pre>
     *
     * <code>.google.protobuf.Timestamp due_at = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDueAtFieldBuilder() {
      if (dueAtBuilder_ == null) {
        dueAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDueAt(),
                getParentForChildren(),
                isClean());
        dueAt_ = null;
      }
      return dueAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.chengpan.proto.Task)
  }

  // @@protoc_insertion_point(class_scope:com.github.chengpan.proto.Task)
  private static final com.github.chengpan.proto.Task DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.chengpan.proto.Task();
  }

  public static com.github.chengpan.proto.Task getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Task>
      PARSER = new com.google.protobuf.AbstractParser<Task>() {
    @java.lang.Override
    public Task parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Task(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Task> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Task> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.chengpan.proto.Task getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

