// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package com.github.chengpan.proto;

public interface TaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.chengpan.proto.TaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string err_msg = 1;</code>
   * @return The errMsg.
   */
  java.lang.String getErrMsg();
  /**
   * <code>string err_msg = 1;</code>
   * @return The bytes for errMsg.
   */
  com.google.protobuf.ByteString
      getErrMsgBytes();
}
