// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package com.github.chengpan.proto;

public interface TaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.chengpan.proto.TaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.github.chengpan.proto.Task task = 1;</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.com.github.chengpan.proto.Task task = 1;</code>
   * @return The task.
   */
  com.github.chengpan.proto.Task getTask();
  /**
   * <code>.com.github.chengpan.proto.Task task = 1;</code>
   */
  com.github.chengpan.proto.TaskOrBuilder getTaskOrBuilder();

  /**
   * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
   * @return The action.
   */
  com.github.chengpan.proto.TaskRequest.Action getAction();
}
