// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package com.github.chengpan.proto;

/**
 * Protobuf type {@code com.github.chengpan.proto.TaskRequest}
 */
public final class TaskRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.chengpan.proto.TaskRequest)
    TaskRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskRequest.newBuilder() to construct.
  private TaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskRequest() {
    action_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TaskRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaskRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.github.chengpan.proto.Task.Builder subBuilder = null;
            if (task_ != null) {
              subBuilder = task_.toBuilder();
            }
            task_ = input.readMessage(com.github.chengpan.proto.Task.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(task_);
              task_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            action_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_TaskRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_TaskRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.chengpan.proto.TaskRequest.class, com.github.chengpan.proto.TaskRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code com.github.chengpan.proto.TaskRequest.Action}
   */
  public enum Action
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * will create or update
     * </pre>
     *
     * <code>PUT = 0;</code>
     */
    PUT(0),
    /**
     * <code>DELETE = 1;</code>
     */
    DELETE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * will create or update
     * </pre>
     *
     * <code>PUT = 0;</code>
     */
    public static final int PUT_VALUE = 0;
    /**
     * <code>DELETE = 1;</code>
     */
    public static final int DELETE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Action valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Action forNumber(int value) {
      switch (value) {
        case 0: return PUT;
        case 1: return DELETE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Action> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Action>() {
            public Action findValueByNumber(int number) {
              return Action.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.chengpan.proto.TaskRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Action[] VALUES = values();

    public static Action valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Action(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.chengpan.proto.TaskRequest.Action)
  }

  public static final int TASK_FIELD_NUMBER = 1;
  private com.github.chengpan.proto.Task task_;
  /**
   * <code>.com.github.chengpan.proto.Task task = 1;</code>
   * @return Whether the task field is set.
   */
  @java.lang.Override
  public boolean hasTask() {
    return task_ != null;
  }
  /**
   * <code>.com.github.chengpan.proto.Task task = 1;</code>
   * @return The task.
   */
  @java.lang.Override
  public com.github.chengpan.proto.Task getTask() {
    return task_ == null ? com.github.chengpan.proto.Task.getDefaultInstance() : task_;
  }
  /**
   * <code>.com.github.chengpan.proto.Task task = 1;</code>
   */
  @java.lang.Override
  public com.github.chengpan.proto.TaskOrBuilder getTaskOrBuilder() {
    return getTask();
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  private int action_;
  /**
   * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
   * @return The enum numeric value on the wire for action.
   */
  @java.lang.Override public int getActionValue() {
    return action_;
  }
  /**
   * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
   * @return The action.
   */
  @java.lang.Override public com.github.chengpan.proto.TaskRequest.Action getAction() {
    @SuppressWarnings("deprecation")
    com.github.chengpan.proto.TaskRequest.Action result = com.github.chengpan.proto.TaskRequest.Action.valueOf(action_);
    return result == null ? com.github.chengpan.proto.TaskRequest.Action.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (task_ != null) {
      output.writeMessage(1, getTask());
    }
    if (action_ != com.github.chengpan.proto.TaskRequest.Action.PUT.getNumber()) {
      output.writeEnum(2, action_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (task_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTask());
    }
    if (action_ != com.github.chengpan.proto.TaskRequest.Action.PUT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, action_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.chengpan.proto.TaskRequest)) {
      return super.equals(obj);
    }
    com.github.chengpan.proto.TaskRequest other = (com.github.chengpan.proto.TaskRequest) obj;

    if (hasTask() != other.hasTask()) return false;
    if (hasTask()) {
      if (!getTask()
          .equals(other.getTask())) return false;
    }
    if (action_ != other.action_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTask()) {
      hash = (37 * hash) + TASK_FIELD_NUMBER;
      hash = (53 * hash) + getTask().hashCode();
    }
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + action_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.chengpan.proto.TaskRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.chengpan.proto.TaskRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.chengpan.proto.TaskRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.chengpan.proto.TaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.chengpan.proto.TaskRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.chengpan.proto.TaskRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.chengpan.proto.TaskRequest)
      com.github.chengpan.proto.TaskRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_TaskRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_TaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.chengpan.proto.TaskRequest.class, com.github.chengpan.proto.TaskRequest.Builder.class);
    }

    // Construct using com.github.chengpan.proto.TaskRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (taskBuilder_ == null) {
        task_ = null;
      } else {
        task_ = null;
        taskBuilder_ = null;
      }
      action_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.chengpan.proto.Message.internal_static_com_github_chengpan_proto_TaskRequest_descriptor;
    }

    @java.lang.Override
    public com.github.chengpan.proto.TaskRequest getDefaultInstanceForType() {
      return com.github.chengpan.proto.TaskRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.chengpan.proto.TaskRequest build() {
      com.github.chengpan.proto.TaskRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.chengpan.proto.TaskRequest buildPartial() {
      com.github.chengpan.proto.TaskRequest result = new com.github.chengpan.proto.TaskRequest(this);
      if (taskBuilder_ == null) {
        result.task_ = task_;
      } else {
        result.task_ = taskBuilder_.build();
      }
      result.action_ = action_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.chengpan.proto.TaskRequest) {
        return mergeFrom((com.github.chengpan.proto.TaskRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.chengpan.proto.TaskRequest other) {
      if (other == com.github.chengpan.proto.TaskRequest.getDefaultInstance()) return this;
      if (other.hasTask()) {
        mergeTask(other.getTask());
      }
      if (other.action_ != 0) {
        setActionValue(other.getActionValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.chengpan.proto.TaskRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.chengpan.proto.TaskRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.github.chengpan.proto.Task task_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.chengpan.proto.Task, com.github.chengpan.proto.Task.Builder, com.github.chengpan.proto.TaskOrBuilder> taskBuilder_;
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     * @return Whether the task field is set.
     */
    public boolean hasTask() {
      return taskBuilder_ != null || task_ != null;
    }
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     * @return The task.
     */
    public com.github.chengpan.proto.Task getTask() {
      if (taskBuilder_ == null) {
        return task_ == null ? com.github.chengpan.proto.Task.getDefaultInstance() : task_;
      } else {
        return taskBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     */
    public Builder setTask(com.github.chengpan.proto.Task value) {
      if (taskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        task_ = value;
        onChanged();
      } else {
        taskBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     */
    public Builder setTask(
        com.github.chengpan.proto.Task.Builder builderForValue) {
      if (taskBuilder_ == null) {
        task_ = builderForValue.build();
        onChanged();
      } else {
        taskBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     */
    public Builder mergeTask(com.github.chengpan.proto.Task value) {
      if (taskBuilder_ == null) {
        if (task_ != null) {
          task_ =
            com.github.chengpan.proto.Task.newBuilder(task_).mergeFrom(value).buildPartial();
        } else {
          task_ = value;
        }
        onChanged();
      } else {
        taskBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     */
    public Builder clearTask() {
      if (taskBuilder_ == null) {
        task_ = null;
        onChanged();
      } else {
        task_ = null;
        taskBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     */
    public com.github.chengpan.proto.Task.Builder getTaskBuilder() {
      
      onChanged();
      return getTaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     */
    public com.github.chengpan.proto.TaskOrBuilder getTaskOrBuilder() {
      if (taskBuilder_ != null) {
        return taskBuilder_.getMessageOrBuilder();
      } else {
        return task_ == null ?
            com.github.chengpan.proto.Task.getDefaultInstance() : task_;
      }
    }
    /**
     * <code>.com.github.chengpan.proto.Task task = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.chengpan.proto.Task, com.github.chengpan.proto.Task.Builder, com.github.chengpan.proto.TaskOrBuilder> 
        getTaskFieldBuilder() {
      if (taskBuilder_ == null) {
        taskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.chengpan.proto.Task, com.github.chengpan.proto.Task.Builder, com.github.chengpan.proto.TaskOrBuilder>(
                getTask(),
                getParentForChildren(),
                isClean());
        task_ = null;
      }
      return taskBuilder_;
    }

    private int action_ = 0;
    /**
     * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
     * @param value The enum numeric value on the wire for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionValue(int value) {
      
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.github.chengpan.proto.TaskRequest.Action getAction() {
      @SuppressWarnings("deprecation")
      com.github.chengpan.proto.TaskRequest.Action result = com.github.chengpan.proto.TaskRequest.Action.valueOf(action_);
      return result == null ? com.github.chengpan.proto.TaskRequest.Action.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(com.github.chengpan.proto.TaskRequest.Action value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      action_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.chengpan.proto.TaskRequest.Action action = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      
      action_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.chengpan.proto.TaskRequest)
  }

  // @@protoc_insertion_point(class_scope:com.github.chengpan.proto.TaskRequest)
  private static final com.github.chengpan.proto.TaskRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.chengpan.proto.TaskRequest();
  }

  public static com.github.chengpan.proto.TaskRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskRequest>
      PARSER = new com.google.protobuf.AbstractParser<TaskRequest>() {
    @java.lang.Override
    public TaskRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TaskRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.chengpan.proto.TaskRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

